"""initial tables

Revision ID: e9300e2335e5
Revises: 86ab555a4976
Create Date: 2026-06-09 18:10:15.104815
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'e9300e2335e5'
down_revision: Union[str, None] = '86ab555a4976'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
